### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by CerenB** [Remi-Gau/matlab_checkcode#1]
sorry to ask but i couldn't follow from the ReadMe file, how to install the required repos.
I have matlab 2016b
> I forked into matlab_checkcode. Made a clone in my local. 
> Then, I do not know how to reach to mpm repo. Is it by typing `mpm install matlab_checkcode -u https://github.com/Remi-Gau/matlab_checkcode.git` in matlab prompt?

**Comment by Remi-Gau** [comment]
will find a work around for 2016b or at least make it fail more gracefully
